version: '3.9'

services:
  todo-api:
    build: ./todo-api
    ports:
      - "3000:3000"
  todo-app:
    build: ./todo-app
    ports:
      - "80:80"
    environment:
      - BACKEND_URL=http://localhost:3000